CREATE TABLE OFFER(
    ID INT PRIMARY KEY NOT NULL,
    ROOMID INT REFERENCES ROOM(ID) NOT NULL,
    PRICE DOUBLE PRECISION NOT NULL,
    DESCRIPTION VARCHAR(2000) NOT NULL,
    NUMBEROFPEOPLE INT NOT NULL,
    IMAGE VARCHAR(500)
);
