CREATE TABLE RESERVATION(
    ID INT PRIMARY KEY NOT NULL,
    CLIENTID INT REFERENCES CLIENT(ID) NOT NULL,
    ROOMID INT REFERENCES ROOM(ID) NOT NULL,
    BEGINING DATE NOT NULL,
    ENDING DATE NOT NULL
);
